// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHRvgKuDWvK9gLErJOoWJLYlTU8J9mJEo',
    appId: '1:23888504970:web:057558817e7a9eb50e2573',
    messagingSenderId: '23888504970',
    projectId: 'chat-app-4b191',
    authDomain: 'chat-app-4b191.firebaseapp.com',
    storageBucket: 'chat-app-4b191.appspot.com',
    measurementId: 'G-9WJJ7BVNZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPPbXW_fezJdvkh6P3PaN8_G3N6SE_67k',
    appId: '1:23888504970:android:202145fa24ae64990e2573',
    messagingSenderId: '23888504970',
    projectId: 'chat-app-4b191',
    storageBucket: 'chat-app-4b191.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6SNSaD3w-2uPrBW5v0im7wkdaPbcdQOs',
    appId: '1:23888504970:ios:d24721c9c1d7dd700e2573',
    messagingSenderId: '23888504970',
    projectId: 'chat-app-4b191',
    storageBucket: 'chat-app-4b191.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6SNSaD3w-2uPrBW5v0im7wkdaPbcdQOs',
    appId: '1:23888504970:ios:d24721c9c1d7dd700e2573',
    messagingSenderId: '23888504970',
    projectId: 'chat-app-4b191',
    storageBucket: 'chat-app-4b191.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHRvgKuDWvK9gLErJOoWJLYlTU8J9mJEo',
    appId: '1:23888504970:web:187245c6d8e05d310e2573',
    messagingSenderId: '23888504970',
    projectId: 'chat-app-4b191',
    authDomain: 'chat-app-4b191.firebaseapp.com',
    storageBucket: 'chat-app-4b191.appspot.com',
    measurementId: 'G-98ZN355K4F',
  );
}
